
name: la_voz_de_la_cura_divina
description: Una aplicación de radio para La Voz de la Cura Divina.
version: 1.0.0+43
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.42
  audio_service: ^0.18.0
  audio_session: ^0.1.10
  provider: ^6.1.2
  url_launcher: ^6.0.9
  marquee: ^2.3.0 
  just_audio_background: ^0.0.1-beta.13
  share_plus: ^7.0.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.1
  loading_animation_widget: ^1.3.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/iconolavoz.png
    - assets/fondovozdacura.png

flutter_launcher_icons:
  android: true
 
  image_path: "assets/iconolavoz.png"
  adaptive_icon_background: "#FFFFFF"  # Fondo blanco explícito
  adaptive_icon_foreground: "assets/iconolavoz.png"


